### ISSUE TITLE
Add 2 links about searching algorithms

### ISSUE THREAD

**Issue by xDidier901** [xDidier901/PrintMyName#8]

**Comment by amiresp** [comment]
hi @xDidier901 , Do you mean the 2 search algorithms for names in the list?

**Comment by xDidier901** [comment]
I mean two searching algorithms just as reference (binary search, linear serch, etc.) just in case someone wants to learn something new :)

**Comment by amiresp** [comment]
I didn't get what you wanted
But I think this link is useful
https://stackoverflow.com/questions/22697936/binary-search-in-javascript

**Comment by amiresp** [comment]
OoooOOHHH
Now I understand what happened
check this : https://medium.com/@jeffrey.allen.lewis/javascript-algorithms-explained-binary-search-25064b896470

**Comment by xDidier901** [comment]
Yeap, exactly like that :)
Add the link to the index file so other people can learn something new !

**Comment by amiresp** [comment]
I think you like the changes ;)

**Comment by xDidier901** [comment]
Nice :)
